{% set version = '0.8-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ctv
  version: {{ version|replace("-", "_") }}

source:
  fn: ctv_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ctv_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ctv/ctv_{{ version }}.tar.gz
  sha256: 16f377a6f15d43a6ca8b3933a60faf63b69d0966f011032862b55df5be2f03af


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: XML
requirements:
  build:

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ctv')"           # [not win]
    - "\"%R%\" -e \"library('ctv')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ctv
  license: GPL-2 | GPL-3
  summary: 'Infrastructure for task views to CRAN-style repositories: Querying task views and
    installing the associated packages (client-side tools), generating HTML pages and
    storing task view information in the repository (server-side tools).'

  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: ctv
# Version: 0.8-3
# Date: 2017-10-07
# Title: CRAN Task Views
# Authors@R: c(person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org", comment = c(ORCID = "0000-0003-0918-3766")), person(given = "Kurt", family = "Hornik", role = "aut", email = "Kurt.Hornik@R-project.org"))
# Description: Infrastructure for task views to CRAN-style repositories: Querying task views and installing the associated packages (client-side tools), generating HTML pages and storing task view information in the repository (server-side tools).
# Depends: R (>= 2.13.0), utils
# Suggests: XML
# License: GPL-2 | GPL-3
# NeedsCompilation: no
# Packaged: 2017-10-08 07:47:14 UTC; hornik
# Author: Achim Zeileis [aut, cre] (<https://orcid.org/0000-0003-0918-3766>), Kurt Hornik [aut]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-10-08 09:50:54

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
