travis:
  secure:
    BINSTAR_TOKEN: bkQil3TGAJYU2vAl2RYy5jZImtQlqmhBMXl5unREO9cN8R2h0XSeuLU+meCAC9WXaDORyiRZVFyl7Sbtz8xHHydQYIDIfPlHVfOUsil3eZbcV6NgL0L8N8Vt0RJGQP6L23mmTQ/Fp2TQ0NbVuOKhjCvgaJNzT7OUiqFc6HbuzrcE+lbeEPXa4VJYGWU+wfCuA7loJgHMJkW19LaYikAcUYQduhbiEU8akosoKLIbXcR9v58+L9RTO9GMQCND0acIP333t9XTc7n914mcDsYvkvSleduqCBHOIAiklf9C/x16CbiSTEfCMTD4uu61BU5S5TUrUCFanAMHX+OgcMJIfK3nQNPQsMOjQ2YZdWXl0NffGuaJ2pxef1VPKStQRRF+gGI4ufvPtOkYFmMhp3h3L39nOyrK4wJOdhdjj+bYI+NcYXB8Mx+VGUhQ40+OZfI0ZTSeSEMPhkKGFJe+nMXYuX5uvDIqDASJ1WM8GrOV6G1fMXX+1v0qtbwNAzs4XHCiLJ3URYjY8lyfNrb58TVZMYqR80Nt4ln2n9Y0tO1xhJ+LQbPpLWVdBcuhuByYKfAl1JlnsVua/tkOeVPMR80KXPfjzrp0kTHnD2JixTS858D4WmuqtL1ASfut496xBF79WjvDnyoDqduHtXE2qdPrJCEvcQcjdaaj7DacSO+RciA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
