travis:
  secure:
    BINSTAR_TOKEN: nVhSSJUrOFEkoc2D3D+lAwh2r7hwI4iD5s+s58yjy4BDzKl6Znydm98gvK6/4+JuPHudg4kSMhpmx0OeXLibZV+DFpCU1rfU2DMW+k1vuraGbiJhpRAaf9oFazJ6HeFmNGg99ztqu4cYG804vffSShO6pRwgCf0GIxdN+Po+5bduz63ttMmUN+mVaakepjCmd+kvV0WGer1Ro/OXHqgQbhtvJ/5O/ftP3DH4NUb7Lnh+/EX+xHVI1EEQ/0+vkrYp+WowDbdrQ38GtIkSVJO0vXZZrGe1Ui2lDhJjjTEF2/sDOSmoSa54WiuLil4UrdD72Y1H7gVAS1eig867uaS7/qqYOZvOJFKy6h4ozcM/N4sA3b7s5mm94NTvpe4XIZFYOJQL/SBiPaQOP3cuOf7Cvi9CEFVZGk9GnWBmjyz37JCm4pFT4pG0CrdrRLqR1fdhayOy/yGudrdfHgkWev0NWK9BlPkmDEb9+V591Uf/K5dI6oNWVxf0WZnEP2vGdA2mVNxi/aszYbwmz1b0shmKksVvPn1gNuXEvlxIGcuXnsCaq/JPYggE7W7mSC974KPasMDadvDN5aESOrDs1Z+Z4pOfvZlriO5JXVMwT2+HCTF2bakuYpWi9ZM830qjgagcf1Ueix5r0S+GseCmJlVdw7L5LZAJY1/9K5GAAI7q0tY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
