travis:
  secure:
    BINSTAR_TOKEN: IJC0uLEo0B5+59AZDcitMlwS8aGKVGJigEqaCckzvliQnMb58KWNE3H0H/uUne4EcKzJrVCZzJV24rHrfK5RjrfggOQzdHBCI0kDtOw4OYTQUQ4+VPMTY6oyj+D2nQfDuJKUZEco07rN9LOoWPy0bTmcGeLOsXnpvbPloGAxGmRy5X9+IFtMM8pkQxySuu3vs4iOTNFtPK1WKR6jrjbLVeDptFhvni9AXrRhlv8D7dQz3oyhVH5+qa9zVtYKvrjZioP8+gbb5nu5iNXd78Xo9ZtWGzJVxrRsO1QJRk0ZXRukv7/sRLwNEnpY9DFlvxxbZOq224D2bdXDyxWV6Pc6O0dq1z9XPn4LjRX3X03qgm9wVLwptPQYnhy1XljVAEeCw96SNA4QLIyBE7OTu1ryf1gjP1YbQBG7rVAMT0KdukYK06fEAvy0I/w21er8o/Cmjzmlx+HKskozfnta5KeuD6f8ANmovwmZ0Qj16ByaWfG7uaifY85lu7GUnCfLqeg1yiGsEuQTa+HZJSmCe8s2U/xH/chzRPHCVa0o+/YKBZfEkVJGm3AjotuItMNqReRoql0KnIW5tK27vkP5PcN5XQF1kVccyrBFGut+LfO6b2EF4FzaLI/mUPc0gflIUUiToqorvQcdNsQ/HkBx+NHNi1T88gYcgBfKVT+dYasRmB4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
